### PR TITLE
commit pop-up

### PR DESCRIPTION
**Pull request by tri220698**

### CODE REVIEW

**Comment by tri220698** [comment]
ready

**Comment by tri220698** [comment]
ready

**Comment by tri220698** [comment]
ready

**Comment by chienpv-0644** [comment]
ready

**Comment by chienpv-0644** [comment]
ready

**Comment by chienpv-0644** [comment]
ready

**Comment by chienpv-0644** [comment]
ready

**Comment by tri220698** [comment]
ready

**Pull request merged**
